///PENDINGS

/// IN VIEW REQUESTS TO CHECK IF A USER IS ALREADY PRESENT IN GROUP

/// WHAT IF USER CLICKS ON A LINK BUT NOT LOGGED IN CURRENTLY

/// CREATE ANOTHER CIRCLE INSIDE A CIRCLE

/// ANONYMOUS LOGIN ?
